x-server-node-template: &x-server-node-template
  restart: always
  image: snowflakeid_arena:latest
  networks:
    - backend
    - proxy
  depends_on:
    - etcd_node1
    - etcd_node2
    - etcd_node3

x-etcd-template: &x-etcd-template
  restart: always
  image: quay.io/coreos/etcd:v3.5.18
  networks:
    - backend
  expose:
    - "2379"
    - "2380"
  logging:
    driver: "json-file"
    options:
      max-size: "1m"
      max-file: "5"
  
services:
  server_node1:
    <<: *x-server-node-template
    container_name: server_node1
    ports:
      - 50052:50051

  server_node2:
    <<: *x-server-node-template
    container_name: server_node2
    ports:
      - 50053:50051

  server_node3:
    <<: *x-server-node-template
    container_name: server_node3
    ports:
      - 50054:50051

  etcd_node1:
    <<: *x-etcd-template
    container_name: etcd_node1
    volumes:
      - etcd_data1:/etcd_data
    command:
      - etcd
      - --name=etcd1
      - data-dir=/etcd_data
      - --advertise-client-urls=http://etcd_node1:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd_node1:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd1=http://etcd_node1:2380,etcd2=http://etcd_node2:2380,etcd3=http://etcd_node3:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster-1

  etcd_node2:
    <<: *x-etcd-template
    container_name: etcd_node2
    volumes:
      - etcd_data2:/etcd_data
    command:
      - etcd
      - --name=etcd2
      - data-dir=/etcd_data
      - --advertise-client-urls=http://etcd_node2:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd_node2:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd1=http://etcd_node1:2380,etcd2=http://etcd_node2:2380,etcd3=http://etcd_node3:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster-1
  
  etcd_node3:
    <<: *x-etcd-template
    container_name: etcd_node3
    volumes:
      - etcd_data3:/etcd_data
    command:
      - etcd
      - --name=etcd3
      - data-dir=/etcd_data
      - --advertise-client-urls=http://etcd_node3:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd_node3:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd1=http://etcd_node1:2380,etcd2=http://etcd_node2:2380,etcd3=http://etcd_node3:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster-1


  envoy:
    restart: always
    container_name: envoy
    image: envoyproxy/envoy:v1.73.7
    networks:
      - proxy
    ports:
      - "10000:10000"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro

networks:
  backend:
  proxy:

volumes:
  etcd_data1:
  etcd_data2:
  etcd_data3:
